<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">

</head>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<body>
<nav class="navbar navbar-expand-lg navbar-light d-flex navbar-css" style="background-color: rgb(240, 224, 190);">
    <a class="navbar-brand pr-5" href="all">Safari Animals</a>

    <div class="d-flex w-75 p-3 ml-5" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto justify-content-between">
            <li class="nav-item">
                <a class="nav-link text-dark" href="all">Home </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="about">About</a>
            </li>
         </ul>
    <a href="createForm" class="btn btn-dark ml-auto">Create New Safari Animal</a>
    </div>
</nav>

<div class="spacing"></div>

<div class="row mt-5">
    <div class="left-side">
    </div>
    <div class="right-side">
        <h1 class="pt-5 pb-5">Our Mission</h1>
        <h6 class="pt-5">This site serves as an educational resource to those who are interested in learning more
            about animals you may encounter on a safari. Whether your actively planning to see them
            in person, or just wondering about them, we provide you with key information about each
            animal. By clicking on the images you can get an in depth
            description of the animal and perhaps learn some of its history too!
        </h6>

    </div>

</div>


</body>
</html>